name: RDP on Windows

on:
  workflow_dispatch: # يضيف زر "Run workflow" في واجهة GitHub

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Start RDP
      run: |
        # تثبيت Chocolatey
        Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

        # تثبيت ngrok
        choco install ngrok -y

        # تكوين ngrok باستخدام التوكن الخاص بك
        ngrok authtoken 2j3sQeJmgjw6ytNyBcY7cZO3wJe_32QMDM5HsgkCZ7GHVFN6a
        ngrok tcp 3389 &

        # إعداد RDP
        netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0

        # إنشاء مستخدم وتعيين كلمة مرور
        $username = "rdpuser"
        $password = "psad34356"
        net user $username $password /add
        net localgroup administrators $username /add

        # الحصول على عنوان ngrok
        Start-Sleep -Seconds 10
        $ngrok_url = (Invoke-WebRequest -Uri http://127.0.0.1:4040/api/tunnels -UseBasicParsing | ConvertFrom-Json).tunnels[0].public_url
        Write-Output "RDP URL: $ngrok_url"
        Write-Output "Username: $username"
        Write-Output "Password: $password"

        # تشغيل الجلسة لمدة ساعتين (يمكن تعديل الوقت حسب الحاجة)
        Start-Sleep -Seconds 7200 # 2 ساعات
